import DBUtils from "./DBUtils.js";

class  DRHindrances {
  private dbUtils: DBUtils | null = null;

  constructor() {
    this.dbUtils = new DBUtils();
  }

  getDBHindrances = (res: { send: (arg0: any[]) => void; }, next: (arg0: any) => any) => {
    try {
      let db = this.dbUtils.getDb();

      const select = db.prepare("SELECT * FROM hindrances");
      const results = select.all();
      res.send(results);
    } catch (err) {
      console.error(err);
      return next(err);
    }
  };

  init = (res: { send: (arg0: string) => void; }, next: (arg0: any) => any) => {
    try {
      let db = this.dbUtils.getDb();
      const create = db.prepare(
        "CREATE TABLE IF NOT EXISTS hindrances (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT, name TEXT, summary TEXT, desc TEXT, source TEXT)"
      );
      create.run();

      const hindrances = [
        { type: "Minor", name: "All Thumbs", summary: "-2 to use mechanical or electrical devices.", desc: "Due to upbringing, lack of exposure, or pure bad luck, some individuals are 'all thumbs' when it comes to mechanical or technological devices. All Thumbs inflicts a -2 penalty when using mechanical or electrical devices. If he rolls a Critical Failure while using such a device (and it doesn't already have a built-in effect), it's broken. If the GM feels it's appropriate, it can be fixed with a Repair roll and 1d6 hours.", source: "SWADE" },
        { type: "Minor", name: "All Thumbs", summary: "-2 to use mechanical or electrical devices.", desc: "Due to upbringing, lack of exposure, or pure bad luck, some individuals are 'all thumbs' when it comes to mechanical or technological devices. All Thumbs inflicts a -2 penalty when using mechanical or electrical devices. If he rolls a Critical Failure while using such a device (and it doesn't already have a built-in effect), it's broken. If the GM feels it's appropriate, it can be fixed with a Repair roll and 1d6 hours.", source: "SWADE" },
        { type: "Minor", name: "Anemic", summary: "-2 Vigor when resisting Fatigue.", desc: "Anemic characters are particularly susceptible to sickness, disease, environmental effects, and fatigue. They subtract 2 from Vigor rolls made to resist Fatigue (see Hazards, startingon page 125).", source: "SWADE" },
        { type: "Major", name: "Arrogant", summary: "Likes to dominate his opponent, challenge the most powerful foe in combat.", desc: "Your hero doesn't think he's the best'heknows he is. Whether it's swordsmanship, kung fu, or painting, few compare to his skills and he flaunts it every chance he gets. Winning isn't enough for this champion. He wants to dominate his opponent and prove there's no one better. He's the kind offighter who disarms an opponent in a duel just to pick the sword up and hand it backwith a smirk. Arrogant individuals look for the greatest threat in battle, hacking their way through lesser minions only because they're in the way.", source: "SWADE" },
        { type: "Minor/Major", name: "Bad Eyes", summary: "-1 to all Trait rolls dependent on vision, or -2 as a Major Hindrance. Eyewear negates penalty but have a 50% chance of breaking when the hero suffers trauma.", desc: "Your hero's eyes aren't what they used to be. He suffers a -1 penalty to any Trait roll dependent on vision (such as ranged attacksand Notice rolls) or -2 as a Major Hindrance. In settings where glasses are available, they negate the penalty when worn. If lost or broken during a combat (generally a 50% chance when he's Wounded, falls, or suffers some other trauma), the character is Distracted (and Vulnerable if a Major Hindrance) until the end of their next turn.", source: "SWADE" },
        { type: "Major", name: "Bad Luck", summary: "The characters starts with one less Benny per session.", desc: "Your hero is a little less lucky than most. He gets one less Benny per game session than normal. A character cannot have both Bad Luck and the Luck Edge.", source: "SWADE" },
        { type: "Minor", name: "Big Mouth", summary: "Unable to keep secrets and constantly gives away private information.", desc: "Loose lips sink ships, the saying goes. This hero's mouth could drown an armada. The blabbermouth can't keep a secret very well. He reveals plans and gives away things best kept among friends, usually at the worst possible times.", source: "SWADE" },
        { type: "Major", name: "Blind", summary: "-6 to all tasks that require vision (but choice of a free Edge to offset).", desc: "The individual is completely without sight. He suffers a -6 to all physical tasks that require vision (GM's call). On the plus side, Blind characters gain their choice of a free Edge to compensate for this particularly difficult Hindrance.", source: "SWADE" },
        { type: "Major", name: "Bloodthirsty", summary: "Never takes prisoners.", desc: "Your hero never takes prisoners unless under the direct supervision of a superior. His cold-blooded ruthlessness causes enemies to respond in kind, often costs vital information, creates constant enemies, and may get him in trouble with his superiors or the authorities, depending on the setting.", source: "SWADE" },
        { type: "Minor", name: "Can't Swim", summary: "-2 to swimming (Athletics) rolls; Each inch moved in water costs 3\" of Pace.", desc: "Most people in the 21st century can swim thanks to swimming pools, easy travel to lakes and beaches, or educational efforts. Historically, however, those who weren't raised around a temperate body of water could not. Characters with this Hindrancesuffer a -2 penalty to the Athletics skill when swimming and each inch moved in water costs 3\" of Pace. See Movement (page 92) for more details and Drowning (page 126).", source: "SWADE" },
        { type: "Minor", name: "Cautious", summary: "The character plans extensively and/or is overly careful.", desc: "This planner personifies restraint and carefulness. He never makes rash decisions and likes to plot things out in detail long before any action is taken.", source: "SWADE" },
        { type: "Major", name: "Clueless", summary: "-1 to Common Knowledge and Notice rolls.", desc: "Your hero doesn't pay much attention to the world around him and can't seem to find a haystack in a small pile of needles. He suffers a -1 penalty to Common Knowledge and Notice rolls.", source: "SWADE" },
        { type: "Major", name: "Clumsy", summary: "-2 to Athletics and Stealth rolls.", desc: "Your hero is an uncoordinated klutz who trips over air and is always the last one picked for sports. He subtracts 2 from Athletics and Stealth rolls.", source: "SWADE" },
        { type: "Major", name: "Code of Honor", summary: "The character keeps his word and acts like a gentleman.", desc: "Honor is very important to your character. He keeps his word, doesn't abuse or kill prisoners, and generally tries to operate within his world's particular notion of proper gentlemanly or ladylike behavior.", source: "SWADE" },
        { type: "Major", name: "Curious", summary: "The character wants to know about everything.", desc: "It killed the cat, and it might kill your warrior as well. Curious characters have to check out everything and always want to know what's behind a potential mystery or secret.", source: "SWADE" },
        { type: "Minor", name: "Death Wish", summary: "The hero wants to die after or while completing some epic task.", desc: "Having a death wish doesn't mean your adventurer is suicidal he might just think his life is worth less than some noble but clearly deadly goal. Those with a Death Wish don't throw their lives away for no reason, but when there's achance to complete a goal they do anything - and take any risk to achieve it.", source: "SWADE" },
        { type: "Minor/Major", name: "Delusional", summary: "The individual believes something strange that causes him occasionalor frequent trouble.", desc: "Your hero believes something that is considered quite strange by everyone else. Minor Delusions are harmless or the character generally keeps it to himself (the government puts sedatives in soft drinks, dogs can talk, we're all just characters in some bizarre game, etc.). With a Major Delusion, he expresses his view on the situation frequently and it can occasionally lead to danger (the government is run by aliens, hospitals are deadly, I'm allergic to armor, zombies are my friends).", source: "SWADE" },
        { type: "Minor", name: "Doubting Thomas", summary: "The character doesn't believe in the supernatural, often exposing him to unnecessary risks.", desc: "Some people don't believe in the supernatural until they're halfway down some creature's gullet. Doubting Thomases are skeptics who try their best to rationalize supernatural events. They walk right into danger they don't believe in and look for alternate explanations to every supernatural event. Even after being confronted with undeniable truth, the doubter's mind eventually begins to doubt what he saw, rationalizes it away, or compartmentalizes the event as one of a kind while continuing to doubt the next mystery.", source: "SWADE" },
        { type: "Minor/Major", name: "Driven", summary: "The hero's actions are driven by some important goal or belief.", desc: "A vow is a commitment to others. Driven characters want something for themselves. It may be to protect the realm, become a decorated officer, prove you're the best gladiator in Rome, or the best pilot in the galactic fleet. The Minor version shapes the character and pushes his decisions but either happens rarely or is fairly harmless. As a Major Hindrance it's an overriding desire that comes up frequently or causes peril for the heroine and those around her.", source: "SWADE" },
        { type: "Major", name: "Elderly", summary: "-1 to Pace, running, Agility, Strength, and Vigor. Hero gets 5 extra skill points.", desc: "Your adventurer is getting on in years, but he's not quite ready for the nursing home yet. His Pace is reduced by 1, and he subtracts 1 from running rolls (minimum 1). He also suffers a -1 penalty to Agility, Strength, and Vigor rolls, but not their linked skills. On the plus side, the wisdom of his years grants the hero 5 extra skill points which may be used for any skills linked to Smarts.", source: "SWADE" },
        { type: "Minor/Major", name: "Enemy", summary: "The character has a recurring nemesis.", desc: "Someone out there hates the character and wants him ruined, locked away, or dead. The value of the Hindrance depends on how powerful the enemy is and how often he might show up. A Minor Enemy might be a lone gunslinger out for vengeance or a betrayed brotherhood that's deadly but appears rarely. A Major Enemy might represent powerful authorities, a band of outlaws, or a single very powerful and relentless rival. If the enemy is one day defeated, the GM should gradually work in a replacement, or the hero may buy off the Hindrance by sacrificing an Advance.", source: "SWADE" },
        { type: "Minor/Major", name: "Greedy", summary: "The individual is obsessed with wealth and material possessions.", desc: "A miser measures worth in material possessions or wealth. If a Minor Hindrance, he argues bitterly for more than his fair share of any loot or reward the party might come across. As a Major Hindrance, he fights over anything he considers unfair, and may even kill for it if he feels slighted or covets something he cannot have.", source: "SWADE" },
        { type: "Minor/Major", name: "Habit", summary: "Addicted to something, suffers Fatigue if deprived.", desc: "Your warrior has an annoying or dangerous compulsion. A Minor Habit irritates those around her but isn't dangerous. Maybe she picks her nose, can't stop fiddling with her phone, says \"y'know\" in the middle of every sentence, or chews and smacks her gum loudly and often. Allies avoid her if possible. A Major Habit is a physical or mental addiction of some sort that is debilitating or possibly even deadly. This includes drug use, chronic drinking, or perhaps even an addiction to virtual reality in a high-tech setting. An addict who doesn't get his fix must make a Vigor roll every 24 hours he goes without ortake a level of Fatigue (see page 100). Once every 24 hours, a Healing roll with some sort of appropriate medicine removes one level of Fatigue for four hours. After that the Fatigue returns and can only be recovered with the addicting substance.", source: "SWADE" },
        { type: "Minor/Major", name: "Hard of Hearing", summary: "-4 to Notice sounds; automatic failure if completely deaf.", desc: "Characters who have lost some or all of their hearing have this disadvantage. As a Minor Hindrance, it subtracts 4 from all Notice rolls made to hear, including awaking due to loud noises. A Major Hindrance means the character is deaf. She cannot hear and automatically fails all Notice rolls that depend on hearing. Hearing aids reduce the penalty by 2, but require batteries and have a 50% chance of falling out when he's Wounded, falls, or suffers some other trauma.", source: "SWADE" },
        { type: "Major", name: "Heroic", summary: "The character always helps those in need.", desc: "This noble soul never says no to a person in need. She doesn't have to be happy about it, but she always comes to the rescue of those she feels can't help themselves. She's the first one to run into a burning building, usually agrees to hunt monsters for little or no pay, and is generally a pushover for a sob story.", source: "SWADE" },
        { type: "Minor", name: "Hesitant", summary: "Draw two Action Cards and take the lowest (except Jokers, which may be kept).", desc: "Your hero hesitates in stressful situations. Draw two Action Cards in combat and act on the lowest. If you draw a Joker, use it normally and ignore the Hindrance for the round (hence this being a Minor Hindrance, it actually increases your chances of drawing a Joker!) Hesitant characters cannot take the Quick or Level Headed Edges.", source: "SWADE" },
        { type: "Minor", name: "Illiterate", summary: "The character cannot read or write.", desc: "Your hero cannot read. He can sign his name and knows what a STOP sign says, but little else. He also doesn't know much about math. He can probably do 2 + 2 = 4, but multiplication and the like are beyond him. Illiterate characters can't read or write in any language, by the way, no matter how many they actually speak.", source: "SWADE" },
        { type: "Major", name: "Impulsive", summary: "The hero leaps before he looks.", desc: "The daredevil almost always leaps before he looks. He rarely thinks things through before taking action.", source: "SWADE" },
        { type: "Minor/Major", name: "Jealous", summary: "The individual covets what others have.", desc: "Insecurity leads to envy of others accomplishments or being overly possessive of what this disgruntled soul feels belongs to him. He often complains, pouts, covets others possessions or accolades, claims credit for another's work, disobeys commands, and generally causes problems. As a Minor Hindrance, the character's jealousy is focused on one particular subject (such as his 'unrivaled' skill as a pilot or a romantic interest). As a Major Hindrance, the character is jealous of anyone and everyone he feels outshines him. He consistently bad-mouths his rivals, tries to upstage them, or actively plots to discredit those who threaten his ego.", source: "SWADE" },
        { type: "Minor", name: "Loyal", summary: "The hero is loyal to his friends and allies.", desc: "This stalwart defender risks her life for her friends without hesitation. Some Loyal heroes may not act that way, but are the first to come to their friends rescue when they're threatened.", source: "SWADE" },
        { type: "Minor", name: "Mean", summary: "-1 to Persuasion rolls.", desc: "This curmudgeon is ill-tempered and disagreeable. He has trouble doing anything kind for anyone else, must be paid for his troubles, and doesn't accept awards or favors graciously. Besides the obvious roleplaying issues, Mean characters subtract 1 from Persuasion rolls.", source: "SWADE" },
        { type: "Minor", name: "Mild Mannered", summary: "-2 to Intimidation rolls.", desc: "Your milquetoast just isn't threatening. Maybe he's a little doughy around the middle, has a kind face, or a soft voice. Whatever the issue, he has a hard time looking tough. He subtracts 2 when making Intimidation rolls.", source: "SWADE" },
        { type: "Major", name: "Mute", summary: "The hero cannot speak.", desc: "Due to trauma or birth, your character has lost the ability to speak. He can write messages to others when needed, use sign language, or some combination of visual communication. Vison-based communication may require a Notice roll to perceive correctly (illumination and similar penalties apply).", source: "SWADE" },
        { type: "Minor", name: "Obese", summary: "Size +1, Pace -1 and running die of d4. Treat Str as one die type lower for Min Str.", desc: "Those who carry their weight well have the Brawny Edge. Those who don't are Obese. A character cannot be both Brawny and Obese, and this Hindrance can't increase your Size above +3.  An Obese hero's Size (and therefore Toughness) increase by +1. His Pace is reduced by 1, and his running die one die type (minimum d4). Strength is considered one die type less (minimum d4) for armor and worn gear (not weapons). They may also have difficulty finding armor or clothing that fits or entering confined spaces.", source: "SWADE" },
        { type: "Minor/Major", name: "Obligation", summary: "The character has a weekly obligation of 20 (Minor) to 40 (Major) hours.", desc: "Your hero has a responsibility she must attend to on a daily or regular basis. It could be a job, volunteer work, taking care of family or friends, etc. The Obligation consumes about 20 hours most weeks, or 40+ for the Major version. Exactly what that entails should be discussed between the player and the Game Master.", source: "SWADE" },
        { type: "Major", name: "One Arm", summary: "-4 to tasks (such as Athletics) that require two hands.", desc: "By birth or battle, your hero has lost an arm. Fortunately, his other arm is (now) his 'good' one. Tasks that require two hands, such as some Athletics rolls (GM's call) or using atwo-handed weapon, suffer a -4 modifier.", source: "SWADE" },
        { type: "Major", name: "One Eye", summary: "-2 to actions at 5\" (10 yards) or more distance.", desc: "This veteran lost an eye and has trouble with depth perception. He subtracts 2 from any Trait roll dependent on vision and more than 5\" (10 yards) distant. ", source: "SWADE" },
        { type: "Minor/Major", name: "Outsider", summary: "The character doesn't fit in to the local environment and subtracts 2 fromPersuasion rolls. As a Major Hindrance she has no legal rights or other serious consequences.", desc: "In a society made up of only a few types of people, your hero isn't one of them. A Native American in a Western town, an alien in a scifi game of human marines, or a half-orc ina party of elves, dwarves, and humans are all examples. Locals are likely to raise prices on her, ignore pleas for help, and generally treat her as lower class. Outsiders subtract 2 from Persuasion rolls made to influence those who aren't her own kind. The Major version also means the character has few or no legal rights in the main campaign area. She might be adifferent species among xenophobes, the civilization may be cruel and unenlightened toward strangers, or she might even be an artificial intelligence whose sapience isn't acknowledged by the law.", source: "SWADE" },
        { type: "Major", name: "Overconfident", summary: "The hero believes she can do anything.", desc: "There's nothing out there your hero can't defeat. At least that's what he thinks. He believes he can do most anything and never wants to retreat from a challenge. He's not suicidal, but he certainly takes on more than common sense dictates.", source: "SWADE" },
        { type: "Minor/Major", name: "Pacifist", summary: "Fights only in self-defense as a Minor Hindrance, won't fight at all as Major.", desc: "Your hero absolutely despises violence. Minor pacifism means he only fights when given no other choice and never allows the killing of prisoners or other defenseless victims. Major Pacifists won't fight living characters under any circumstances. They may defend themselves, but won't do anything to permanently harm sapient, living creatures. They may use nonlethal methods (see page 104), but only in self-defense or the defense of others.  Note that undeniably evil creatures, undead, demons, and the like are fair game even for Major Pacifists!", source: "SWADE" },
        { type: "Minor/Major", name: "Phobia", summary: "The character is afraid of something, and subtracts -1/-2 from all Trait rollsin its presence.", desc: "Phobias are overwhelming and irrationalfears that plague a hero's psyche. Whenever a character is in the presence of his phobia (GM's call, but generally sight), he subtracts 1 from all his Trait rolls if it's a Minor Hindrance, and 2 if it's Major. Phobias shouldn't be too obvious; everyoneshould be afraid of vampires, for example, so it's not a phobia, it's common sense. Instead, the phobia usually centers on some random element the mind associates with the event. Remember, phobias are irrational fears.", source: "SWADE" },
        { type: "Minor", name: "Poverty", summary: "Half starting funds and the character is always broke.", desc: "It's said a fool and his money are soon parted. Your hero is one of them. He starts with half the usual money for your setting and just can't seem to hang on to funds acquired after play begins. In general, the player halves his total funds every game week.", source: "SWADE" },
        { type: "Minor", name: "Quirk", summary: "The individual has some minor but persistent foible that often annoys others.", desc: "This individual has some minor foible that is usually humorous but can occasionally cause him real trouble. A swashbuckler may always try to slash his initials on his foes, a dwarf may brag constantly about his culture, or a snobby debutante might not eat, drink, or socialize with the lower class, for example.", source: "SWADE" },
        { type: "Minor/Major", name: "Ruthless", summary: "The character does what it takes to get her way.", desc: "The fanatic will do most anything to accomplish her goals. As a Major Hindrance, she harms anyone and everyone who gets in her way. As a Minor Hindrance, she stops short of true harm to anyone except those who directly oppose her.", source: "SWADE" },
        { type: "Minor/Major", name: "Secret", summary: "The hero has a dark secret of some kind.", desc: "Your hero has a secret she keeps to protect herself or others. As a Minor Hindrance, the secret is troublesome but not life-threatening. The Major version would cause severe problems if discovered. If it ever becomes public knowledge, she should trade it for Enemy, Shamed, Wanted, or another appropriate Hindrance approved by the GM.", source: "SWADE" },
        { type: "Minor/Major", name: "Shamed", summary: "The individual is haunted by some tragic event from her past.", desc: "Something haunts your adventurer. Maybe he made a vow he ddn't keep. Maybe he was defeated in an honorable fight and ordered the death of his foe anyway for some greater principle. Maybe he isn't actually cowardly but once ran from a battle and left others to die. As a Minor Hindrance, the shameful circumstances aren't generally known - it just haunts the hero. He might go out of his way, against all reason, not to repeat the mistake. Or he might give in to the same set of circumstances and hate himself for it. As a Major Hindrance, his deed is well-known - or at least known among those he cares about. The other player characters should be told the tale as soon as possible (preferably at character creation). If not, it should be revealed by nonplayer characters at some point, and occasionally used against the hero.", source: "SWADE" },
        { type: "Minor/Major", name: "Slow", summary: "Pace -1, reduce running die one step. As Major, Pace -2, -2 to Athletics androlls to resist Athletics. Neither may take the Fleet-Footed Edge.", desc: "A disability or past injury has hindered this hero's mobility. As a Minor Hindrance,reduce his Pace by 1 and his running die one step (if already d4, reduce to d4-1). As a Major Hindrance, reduce the running die a step, Pace by 2, and subtract 2 from Athletics rolls and rolls to resist Athletics (such as Tests or Grappling). Slow characters may not take the Fleet-Footed Edge.", source: "SWADE" },
        { type: "Minor", name: "Small", summary: "Size and Toughness are reduced by 1. Size cannot be reduced below -1.", desc: "This adventurer is very skinny, very short, or both. His Size (see page 106) is reduced by 1, which reduces his Toughness as well. Size can't be reduced below 1, but the Toughness penalty remains. A Small half-folk, for example, remains Size -1 and loses a point of Toughness.", source: "SWADE" },
        { type: "Minor", name: "Stubborn", summary: "The character wants his way and rarely admits his mistakes.", desc: "Stubborn individuals always want their way and never admit they're wrong. Even when it's painfully obvious they've made a mistake they try to justify it with half-truths and rationalizations.", source: "SWADE" },
        { type: "Minor/Major", name: "Suspicious", summary: "The individual is paranoid. As a Major Hindrance, allies subtract 2when rolling to Support him.", desc: "Your character is suspicious of everyone. As a Minor Hindrance, his paranoia causes frequent trust issues. He might demand full payment before doing a task, want every agreement in writing, or believe even his friends are out to get him. As a Major Hindrance, Support rolls to aid the distrustful individual are made at -2.", source: "SWADE" },
        { type: "Minor/Major", name: "Thin Skinned", summary: "The character is particularly susceptible to personal attacks. As aMinor Hindrance, he subtracts two when resisting Taunt attacks. As a Major, he subtracts four.", desc: "Personal attacks really get under this individual's skin. As a Minor Hindrance, he subtracts 2 when resisting Taunt attacks. As a Major, he subtracts 4.", source: "SWADE" },
        { type: "Major", name: "Tongue-Tied", summary: "The character often misspeaks or can't get her words out. -1 to Intimidation,Persuasion, and Taunt rolls.", desc: "Your adventurer flubs cool lines (or thinks of them afterwards!), goes off on tangents when he's trying to talk someone into something, and generally miscommunicates most everything he says. He suffers a -1 penalty to Intimidation, Performance, Persuasion, and Taunt rolls that involve speech.", source: "SWADE" },
        { type: "Minor/Major", name: "Ugly", summary: "The character is physically unattractive and subtracts 1 or 2 from Persuasion rolls.", desc: "Attractive people get all the breaks. This unfortunate individual isn't one of them. He subtracts 1 from his Persuasion rolls, or 2 if taken as a Major Hindrance.", source: "SWADE" },
        { type: "Minor/Major", name: "Vengeful", summary: "The adventurer seeks payback for slights against her. As a MajorHindrance, she'll cause physical harm to get it.", desc: "Payback is ...well...bad news for someone, and this adventurer is going to get it. As a Minor Hindrance she usually seeks vengeance legally. The method varies by situation. Some plot and scheme for months while others demand immediate results. Those with the Major version of this Hindrance don't let anything prevent them from a reckoning. This doesn't mean they immediately resort to violence, but their actions always escalate until total and complete satisfaction is achieved.", source: "SWADE" },
        { type: "Minor/Major", name: "Vow", summary: "The individual has pledged himself to some cause.", desc: "The character has sworn an oath to someone or something he believes in. The danger in fulfilling the Vow and how often it might occur determines the level ofthe Hindrance. A Minor Vow might be to serve an order with a broad mandate that rarely conflicts with the party's goals. A Major Vow makes long-term and frequent demands on the servant's time and results in great risks to his life.", source: "SWADE" },
        { type: "Minor/Major", name: "Wanted", summary: "The character is wanted by the authorities.", desc: "Your hero has committed some crime and will be arrested if discovered by the authorities. This assumes the setting actually has laws and police officers to enforce them. The level of the Hindrance depends on how serious the crime was and how active the hunters are. A hero with numerous unpaid parking tickets (in a game wherehe might have to drive occasionally) has a Minor Hindrance, as does someone wanted for more serious crimes away from the main campaign area. Being accused of murder is a Major Hindrance in almost any setting if there's someone around to seek justice (or vengeance).", source: "SWADE" },
        { type: "Major", name: "Yellow", summary: "-2 to Fear checks and resisting Intimidation.", desc: "Not everyone has ice water in their veins. Your hero is squeamish at the sight of blood and gore and terrified of coming to harm. He subtracts 2 from Fear checks and when resisting Intimidation.", source: "SWADE" },
        { type: "Minor/Major", name: "Young", summary: "Minor has 4 attribute points and 10 skill points, extra Benny per session. Major has 3 attribute points, 10 skill points, and two extra Bennies per session.", desc: "The hero is 12-15 years old (in human years adjust this for other races). He has only 4 points to adjust his attributes instead of 5, and 10 skill points instead of 12. He may also have legal restrictions depending on the setting (can't drive, own a firearm, and so on). On the plus side, youths have a fair amount of luck. They draw one extra Benny at the beginning of each game session (this stacks with other Edges such Luck or Great Luck). Most Young characters should also take the Small Hindrance, but it's not mandatory. As a Major Hindrance, the character is Very Young (8 to 11 years old). He has only 3 pointsfor attributes and 10 for skills, and the Small Hindrance. Very Young heroes draw two extra Bennies at the start of each session.", source: "SWADE" },
      ];

      const insert = db.prepare(
        "INSERT INTO hindrances(type, name, summary, desc, source) VALUES (?, ?, ?, ?, ?)"
      );
      hindrances.forEach((hindrance) => {
        insert.run(hindrance.type, hindrance.name, hindrance.summary, hindrance.desc, hindrance.source);
      });
      res.send("Initialized hindrances");
    } catch (err) {
      console.error(err);
      return next(err);
    }
  };

  drop = (res: { send: (arg0: string) => void; }, next: (arg0: any) => any) => {
    try {
      let db = this.dbUtils.getDb();
      const drop = db.prepare("DROP TABLE hindrances");
      drop.run("DROP TABLE hindrance", function (err: string) {
        if (err) {
          console.log(err);
          res.send(err);
        } else {
          console.log("Dropped table");
          res.send("Dropped hindrance table");
        }
      });
    } catch (err) {
      console.error(err);
      return next(err);
    }
  };
}

export default  DRHindrances;
